server:
  port: 8484

spring:
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
firstApp:
  name: ${FIRST_NAME:localhost}
secondApp:
  url: ${SECOND_URL:http://localhost:8485}
  name: ${SECOND_NAME:localhost}
topic:
  json:
    name: t.food.order
  xml:
    name: t.food.orderXml
  protobuf:
    name: t.food.orderProtobuf
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true